(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> "
p3
sS'layer'
p4
S'/home/matt/Dev/web2py/applications/Library_Samples/controllers/invite_tool.py'
p5
sS'code'
p6
S"# -*- coding: utf-8 -*-\n# this file is released under public domain and you can use without limitations\n\n#########################################################################\n## This is a sample controller\n## - index is the default action of any application\n## - user is required for authentication and authorization\n## - download is for downloading files uploaded in the db (does streaming)\n#########################################################################\n\ndef index():\n    return locals()\n    \n    \n    def index():\n\trows = db(db.blog_post).select()\n\tfor row in rows:\n\t\trow.hasMoreToRead = False\n\t\tif len(str(row.body)) > 1500:\n\t\t\trow.body = str(row.body)[:2000] + ' .... '\n\t\t\trow.hasMoreToRead = True\n\treturn locals()\n\t\n\t\ndef getAccountCollection():\n\trows = db(db.accounts).select()\n\treturn response.json([{'name': 'Great Company', 'id':'1234'},\n\t{'name': 'Great Company 2', 'id':'12374'}])\n\nresponse._vars=response._caller(getAccountCollection)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/matt/Dev/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/matt/Dev/web2py/applications/Library_Samples/controllers/invite_tool.py", line 30, in <module>\n  File "/home/matt/Dev/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/matt/Dev/web2py/applications/Library_Samples/controllers/invite_tool.py", line 26, in getAccountCollection\n    rows = db(db.accounts).select()\n  File "/home/matt/Dev/web2py/gluon/packages/dal/pydal/base.py", line 906, in __getattr__\n    return super(DAL, self).__getattr__(key)\n  File "/home/matt/Dev/web2py/gluon/packages/dal/pydal/helpers/classes.py", line 348, in __getattr__\n    raise AttributeError\nAttributeError\n'
p11
s.