(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'Query' object has no attribute 'type'"
p3
sS'layer'
p4
S'/home/matt/Dev/web2py/applications/Library_Samples/controllers/invite_tool.py'
p5
sS'code'
p6
S"\ndef index():\n    return locals()\t\n\t\ndef getAccountCollection():\n\tjson = []\n\trows = db().select(db.accounts.ALL, orderby=db.accounts.name)\n\tfor row in rows:\n\t\tjson.append({'name': row.name, 'id': row.id})\n\t\t\n\treturn response.json(json)\n\t\ndef getInviteeCollection():\n\tjson = []\n\trows = db().select(db.invitees.account_id.contains(request.args), orderby=db.invitees.first_name)\n\tfor row in rows:\n\t\tjson.append({'id': row.id, 'first_name': row.first_name, 'last_name': row.last_name, 'email': row.email})\n\t\t\n\treturn response.json(json)\n\nresponse._vars=response._caller(getInviteeCollection)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/matt/Dev/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/matt/Dev/web2py/applications/Library_Samples/controllers/invite_tool.py", line 21, in <module>\n  File "/home/matt/Dev/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/matt/Dev/web2py/applications/Library_Samples/controllers/invite_tool.py", line 15, in getInviteeCollection\n    rows = db().select(db.invitees.account_id.contains(request.args), orderby=db.invitees.first_name)\n  File "/home/matt/Dev/web2py/gluon/packages/dal/pydal/objects.py", line 1986, in select\n    return adapter.select(self.query,fields,attributes)\n  File "/home/matt/Dev/web2py/gluon/packages/dal/pydal/adapters/sqlite.py", line 122, in select\n    return super(SQLiteAdapter, self).select(query, fields, attributes)\n  File "/home/matt/Dev/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1245, in select\n    sql = self._select(query, fields, attributes)\n  File "/home/matt/Dev/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1074, in _select\n    sql_f = \', \'.join(map(geoexpand, fields))\n  File "/home/matt/Dev/web2py/gluon/packages/dal/pydal/adapters/base.py", line 1071, in geoexpand\n    if isinstance(field.type,str) and field.type.startswith(\'geo\') and isinstance(field, Field):\nAttributeError: \'Query\' object has no attribute \'type\'\n'
p11
s.