(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'module' object has no attribute 'Uuid4'"
p3
sS'layer'
p4
S'/home/matt/Dev/web2py/applications/blog/controllers/invite_tool.py'
p5
sS'code'
p6
S"def index():\n    return locals()\t\n\t\ndef getAccountCollection():\n\tjson = []\n\trows = db().select(db.accounts.ALL, orderby=db.accounts.name)\n\tfor row in rows:\n\t\tjson.append({'name': row.name, 'id': row.id})\n\t\t\n\treturn response.json(json)\n\t\ndef getInviteeCollection():\n\tjson = []\n\trows = db(db.invitees.account_id.contains(request.args)).select(orderby=db.invitees.first_name)\n\tfor row in rows:\n\t\tjson.append({'id': row.id, 'uuid': row.uuid, 'first_name': row.first_name, 'last_name': row.last_name, 'email': row.email})\n\t\t\n\treturn response.json(json)\n\t\ndef postInvitee():\n\tform = SQLFORM(db.invitees)\n\trequest.uuid = uuid.uuid4()\n\tif form.accepts(request, formname=None):\n\t\treturn dict(form=form)\n\telif form.errors:\n\t\treturn TABLE(*[TR(k, v) for k, v in form.errors.items()])\n\nresponse._vars=response._caller(postInvitee)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/matt/Dev/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/matt/Dev/web2py/applications/blog/controllers/invite_tool.py", line 28, in <module>\n  File "/home/matt/Dev/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/matt/Dev/web2py/applications/blog/controllers/invite_tool.py", line 21, in postInvitee\n    form = SQLFORM(db.invitees)\n  File "/home/matt/Dev/web2py/gluon/sqlhtml.py", line 1190, in __init__\n    default = default()\n  File "/home/matt/Dev/web2py/applications/blog/models/db1.py", line 14, in <lambda>\n    Field ( \'uuid\' ,  length = 64 ,  default = lambda : str ( uuid . Uuid4 ())),\nAttributeError: \'module\' object has no attribute \'Uuid4\'\n'
p11
s.