(dp1
S'output'
p2
S"<type 'exceptions.AttributeError'> 'SQLFORM' object has no attribute 'post_vars'"
p3
sS'layer'
p4
S'/home/matt/Dev/web2py/applications/blog/controllers/invite_tool.py'
p5
sS'code'
p6
S"\ndef index():\n    return locals()\t\n\t\ndef getAccountCollection():\n\tjson = []\n\trows = db().select(db.accounts.ALL, orderby=db.accounts.name)\n\tfor row in rows:\n\t\tjson.append({'name': row.name, 'id': row.id})\n\t\t\n\treturn response.json(json)\n\t\ndef getInviteeCollection():\n\tjson = []\n\trows = db(db.invitees.account_id.contains(request.args)).select(orderby=db.invitees.first_name)\n\tfor row in rows:\n\t\tjson.append({'id': row.id, 'first_name': row.first_name, 'last_name': row.last_name, 'email': row.email})\n\t\t\n\treturn response.json(json)\n\t\ndef postInvitee():\n\tform = SQLFORM(db.invitees)\n\tform.post_vars.id = 'asdf'\n\tif form.accepts(request, formname=None):\n\t\treturn request.post_vars\n\telif form.errors:\n\t\treturn TABLE(*[TR(k, v) for k, v in form.errors.items()])\n\nresponse._vars=response._caller(postInvitee)\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/matt/Dev/web2py/gluon/restricted.py", line 227, in restricted\n    exec ccode in environment\n  File "/home/matt/Dev/web2py/applications/blog/controllers/invite_tool.py", line 29, in <module>\n  File "/home/matt/Dev/web2py/gluon/globals.py", line 412, in <lambda>\n    self._caller = lambda f: f()\n  File "/home/matt/Dev/web2py/applications/blog/controllers/invite_tool.py", line 23, in postInvitee\n    form.post_vars.id = \'asdf\'\nAttributeError: \'SQLFORM\' object has no attribute \'post_vars\'\n'
p11
s.